package com.platform.entity;

import java.math.BigDecimal;
import java.util.Date;

public class OfflineOrderInfoPo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.id
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.goods_id
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.order_no
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.order_type
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private Integer orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.order_status
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.payment_status
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private Integer paymentStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.payment_time
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private Date paymentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.payment_no
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private String paymentNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.payment_price
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private BigDecimal paymentPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.order_price
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private BigDecimal orderPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.service_house_name
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private String serviceHouseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.service_time
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private String serviceTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.service_required
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private String serviceRequired;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.problem_description
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private String problemDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.service_type
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private String serviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.service_space
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private String serviceSpace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.service_acreage
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private String serviceAcreage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.service_idea
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private String serviceIdea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.service_air_conditioner_model
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private String serviceAirConditionerModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.service_air_conditioner_type
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private String serviceAirConditionerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.service_furniture
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private String serviceFurniture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.service_house_type
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private String serviceHouseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.service_house_delivery_standards
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private String serviceHouseDeliveryStandards;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.contact_name
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private String contactName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.contact_mobile
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private String contactMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.address
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.create_time
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.update_time
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.create_user_id
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.update_user_id
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private Long updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.defunct
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private Integer defunct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.coupon_id
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private Integer couponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.coupon_price
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private BigDecimal couponPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.channel_id
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private Integer channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.master_worker
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private String masterWorker;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.master_worker_id
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private Long masterWorkerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.is_outer_order
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private Short isOuterOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.outer_merchant_name
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private String outerMerchantName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.outer_service_category
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private String outerServiceCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.outer_service_content
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private String outerServiceContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.outer_service_brand
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private String outerServiceBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.outer_service_combo
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private String outerServiceCombo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nideshop_offline_order_info.batch_no
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    private String batchNo;

    //支付渠道
    private String payChannel;

    //收款账号
    private String shroffAccountNumber;
    //门店id
    private Long storeId;
    //门店名称
    private String storeName;
    //支付方式 1线上支付 2线下支付
    private String payType;
    private String storeAddress;
    private String storeContact;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.id
     *
     * @return the value of nideshop_offline_order_info.id
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.id
     *
     * @param id the value for nideshop_offline_order_info.id
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.goods_id
     *
     * @return the value of nideshop_offline_order_info.goods_id
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.goods_id
     *
     * @param goodsId the value for nideshop_offline_order_info.goods_id
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.order_no
     *
     * @return the value of nideshop_offline_order_info.order_no
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.order_no
     *
     * @param orderNo the value for nideshop_offline_order_info.order_no
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.order_type
     *
     * @return the value of nideshop_offline_order_info.order_type
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.order_type
     *
     * @param orderType the value for nideshop_offline_order_info.order_type
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.order_status
     *
     * @return the value of nideshop_offline_order_info.order_status
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.order_status
     *
     * @param orderStatus the value for nideshop_offline_order_info.order_status
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.payment_status
     *
     * @return the value of nideshop_offline_order_info.payment_status
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public Integer getPaymentStatus() {
        return paymentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.payment_status
     *
     * @param paymentStatus the value for nideshop_offline_order_info.payment_status
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setPaymentStatus(Integer paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.payment_time
     *
     * @return the value of nideshop_offline_order_info.payment_time
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public Date getPaymentTime() {
        return paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.payment_time
     *
     * @param paymentTime the value for nideshop_offline_order_info.payment_time
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setPaymentTime(Date paymentTime) {
        this.paymentTime = paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.payment_no
     *
     * @return the value of nideshop_offline_order_info.payment_no
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public String getPaymentNo() {
        return paymentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.payment_no
     *
     * @param paymentNo the value for nideshop_offline_order_info.payment_no
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setPaymentNo(String paymentNo) {
        this.paymentNo = paymentNo == null ? null : paymentNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.payment_price
     *
     * @return the value of nideshop_offline_order_info.payment_price
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public BigDecimal getPaymentPrice() {
        return paymentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.payment_price
     *
     * @param paymentPrice the value for nideshop_offline_order_info.payment_price
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setPaymentPrice(BigDecimal paymentPrice) {
        this.paymentPrice = paymentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.order_price
     *
     * @return the value of nideshop_offline_order_info.order_price
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public BigDecimal getOrderPrice() {
        return orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.order_price
     *
     * @param orderPrice the value for nideshop_offline_order_info.order_price
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setOrderPrice(BigDecimal orderPrice) {
        this.orderPrice = orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.service_house_name
     *
     * @return the value of nideshop_offline_order_info.service_house_name
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public String getServiceHouseName() {
        return serviceHouseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.service_house_name
     *
     * @param serviceHouseName the value for nideshop_offline_order_info.service_house_name
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setServiceHouseName(String serviceHouseName) {
        this.serviceHouseName = serviceHouseName == null ? null : serviceHouseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.service_time
     *
     * @return the value of nideshop_offline_order_info.service_time
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public String getServiceTime() {
        return serviceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.service_time
     *
     * @param serviceTime the value for nideshop_offline_order_info.service_time
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setServiceTime(String serviceTime) {
        this.serviceTime = serviceTime == null ? null : serviceTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.service_required
     *
     * @return the value of nideshop_offline_order_info.service_required
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public String getServiceRequired() {
        return serviceRequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.service_required
     *
     * @param serviceRequired the value for nideshop_offline_order_info.service_required
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setServiceRequired(String serviceRequired) {
        this.serviceRequired = serviceRequired == null ? null : serviceRequired.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.problem_description
     *
     * @return the value of nideshop_offline_order_info.problem_description
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public String getProblemDescription() {
        return problemDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.problem_description
     *
     * @param problemDescription the value for nideshop_offline_order_info.problem_description
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setProblemDescription(String problemDescription) {
        this.problemDescription = problemDescription == null ? null : problemDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.service_type
     *
     * @return the value of nideshop_offline_order_info.service_type
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.service_type
     *
     * @param serviceType the value for nideshop_offline_order_info.service_type
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setServiceType(String serviceType) {
        this.serviceType = serviceType == null ? null : serviceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.service_space
     *
     * @return the value of nideshop_offline_order_info.service_space
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public String getServiceSpace() {
        return serviceSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.service_space
     *
     * @param serviceSpace the value for nideshop_offline_order_info.service_space
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setServiceSpace(String serviceSpace) {
        this.serviceSpace = serviceSpace == null ? null : serviceSpace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.service_acreage
     *
     * @return the value of nideshop_offline_order_info.service_acreage
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public String getServiceAcreage() {
        return serviceAcreage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.service_acreage
     *
     * @param serviceAcreage the value for nideshop_offline_order_info.service_acreage
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setServiceAcreage(String serviceAcreage) {
        this.serviceAcreage = serviceAcreage == null ? null : serviceAcreage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.service_idea
     *
     * @return the value of nideshop_offline_order_info.service_idea
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public String getServiceIdea() {
        return serviceIdea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.service_idea
     *
     * @param serviceIdea the value for nideshop_offline_order_info.service_idea
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setServiceIdea(String serviceIdea) {
        this.serviceIdea = serviceIdea == null ? null : serviceIdea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.service_air_conditioner_model
     *
     * @return the value of nideshop_offline_order_info.service_air_conditioner_model
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public String getServiceAirConditionerModel() {
        return serviceAirConditionerModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.service_air_conditioner_model
     *
     * @param serviceAirConditionerModel the value for nideshop_offline_order_info.service_air_conditioner_model
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setServiceAirConditionerModel(String serviceAirConditionerModel) {
        this.serviceAirConditionerModel = serviceAirConditionerModel == null ? null : serviceAirConditionerModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.service_air_conditioner_type
     *
     * @return the value of nideshop_offline_order_info.service_air_conditioner_type
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public String getServiceAirConditionerType() {
        return serviceAirConditionerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.service_air_conditioner_type
     *
     * @param serviceAirConditionerType the value for nideshop_offline_order_info.service_air_conditioner_type
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setServiceAirConditionerType(String serviceAirConditionerType) {
        this.serviceAirConditionerType = serviceAirConditionerType == null ? null : serviceAirConditionerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.service_furniture
     *
     * @return the value of nideshop_offline_order_info.service_furniture
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public String getServiceFurniture() {
        return serviceFurniture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.service_furniture
     *
     * @param serviceFurniture the value for nideshop_offline_order_info.service_furniture
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setServiceFurniture(String serviceFurniture) {
        this.serviceFurniture = serviceFurniture == null ? null : serviceFurniture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.service_house_type
     *
     * @return the value of nideshop_offline_order_info.service_house_type
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public String getServiceHouseType() {
        return serviceHouseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.service_house_type
     *
     * @param serviceHouseType the value for nideshop_offline_order_info.service_house_type
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setServiceHouseType(String serviceHouseType) {
        this.serviceHouseType = serviceHouseType == null ? null : serviceHouseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.service_house_delivery_standards
     *
     * @return the value of nideshop_offline_order_info.service_house_delivery_standards
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public String getServiceHouseDeliveryStandards() {
        return serviceHouseDeliveryStandards;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.service_house_delivery_standards
     *
     * @param serviceHouseDeliveryStandards the value for nideshop_offline_order_info.service_house_delivery_standards
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setServiceHouseDeliveryStandards(String serviceHouseDeliveryStandards) {
        this.serviceHouseDeliveryStandards = serviceHouseDeliveryStandards == null ? null : serviceHouseDeliveryStandards.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.contact_name
     *
     * @return the value of nideshop_offline_order_info.contact_name
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.contact_name
     *
     * @param contactName the value for nideshop_offline_order_info.contact_name
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setContactName(String contactName) {
        this.contactName = contactName == null ? null : contactName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.contact_mobile
     *
     * @return the value of nideshop_offline_order_info.contact_mobile
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public String getContactMobile() {
        return contactMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.contact_mobile
     *
     * @param contactMobile the value for nideshop_offline_order_info.contact_mobile
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setContactMobile(String contactMobile) {
        this.contactMobile = contactMobile == null ? null : contactMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.address
     *
     * @return the value of nideshop_offline_order_info.address
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.address
     *
     * @param address the value for nideshop_offline_order_info.address
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.create_time
     *
     * @return the value of nideshop_offline_order_info.create_time
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.create_time
     *
     * @param createTime the value for nideshop_offline_order_info.create_time
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.update_time
     *
     * @return the value of nideshop_offline_order_info.update_time
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.update_time
     *
     * @param updateTime the value for nideshop_offline_order_info.update_time
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.create_user_id
     *
     * @return the value of nideshop_offline_order_info.create_user_id
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.create_user_id
     *
     * @param createUserId the value for nideshop_offline_order_info.create_user_id
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.update_user_id
     *
     * @return the value of nideshop_offline_order_info.update_user_id
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.update_user_id
     *
     * @param updateUserId the value for nideshop_offline_order_info.update_user_id
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.defunct
     *
     * @return the value of nideshop_offline_order_info.defunct
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public Integer getDefunct() {
        return defunct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.defunct
     *
     * @param defunct the value for nideshop_offline_order_info.defunct
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setDefunct(Integer defunct) {
        this.defunct = defunct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.coupon_id
     *
     * @return the value of nideshop_offline_order_info.coupon_id
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public Integer getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.coupon_id
     *
     * @param couponId the value for nideshop_offline_order_info.coupon_id
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setCouponId(Integer couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.coupon_price
     *
     * @return the value of nideshop_offline_order_info.coupon_price
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public BigDecimal getCouponPrice() {
        return couponPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.coupon_price
     *
     * @param couponPrice the value for nideshop_offline_order_info.coupon_price
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setCouponPrice(BigDecimal couponPrice) {
        this.couponPrice = couponPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.channel_id
     *
     * @return the value of nideshop_offline_order_info.channel_id
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public Integer getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.channel_id
     *
     * @param channelId the value for nideshop_offline_order_info.channel_id
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.master_worker
     *
     * @return the value of nideshop_offline_order_info.master_worker
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public String getMasterWorker() {
        return masterWorker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.master_worker
     *
     * @param masterWorker the value for nideshop_offline_order_info.master_worker
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setMasterWorker(String masterWorker) {
        this.masterWorker = masterWorker == null ? null : masterWorker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.master_worker_id
     *
     * @return the value of nideshop_offline_order_info.master_worker_id
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public Long getMasterWorkerId() {
        return masterWorkerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.master_worker_id
     *
     * @param masterWorkerId the value for nideshop_offline_order_info.master_worker_id
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setMasterWorkerId(Long masterWorkerId) {
        this.masterWorkerId = masterWorkerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.is_outer_order
     *
     * @return the value of nideshop_offline_order_info.is_outer_order
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public Short getIsOuterOrder() {
        return isOuterOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.is_outer_order
     *
     * @param isOuterOrder the value for nideshop_offline_order_info.is_outer_order
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setIsOuterOrder(Short isOuterOrder) {
        this.isOuterOrder = isOuterOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.outer_merchant_name
     *
     * @return the value of nideshop_offline_order_info.outer_merchant_name
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public String getOuterMerchantName() {
        return outerMerchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.outer_merchant_name
     *
     * @param outerMerchantName the value for nideshop_offline_order_info.outer_merchant_name
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setOuterMerchantName(String outerMerchantName) {
        this.outerMerchantName = outerMerchantName == null ? null : outerMerchantName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.outer_service_category
     *
     * @return the value of nideshop_offline_order_info.outer_service_category
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public String getOuterServiceCategory() {
        return outerServiceCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.outer_service_category
     *
     * @param outerServiceCategory the value for nideshop_offline_order_info.outer_service_category
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setOuterServiceCategory(String outerServiceCategory) {
        this.outerServiceCategory = outerServiceCategory == null ? null : outerServiceCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.outer_service_content
     *
     * @return the value of nideshop_offline_order_info.outer_service_content
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public String getOuterServiceContent() {
        return outerServiceContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.outer_service_content
     *
     * @param outerServiceContent the value for nideshop_offline_order_info.outer_service_content
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setOuterServiceContent(String outerServiceContent) {
        this.outerServiceContent = outerServiceContent == null ? null : outerServiceContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.outer_service_brand
     *
     * @return the value of nideshop_offline_order_info.outer_service_brand
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public String getOuterServiceBrand() {
        return outerServiceBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.outer_service_brand
     *
     * @param outerServiceBrand the value for nideshop_offline_order_info.outer_service_brand
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setOuterServiceBrand(String outerServiceBrand) {
        this.outerServiceBrand = outerServiceBrand == null ? null : outerServiceBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.outer_service_combo
     *
     * @return the value of nideshop_offline_order_info.outer_service_combo
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public String getOuterServiceCombo() {
        return outerServiceCombo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.outer_service_combo
     *
     * @param outerServiceCombo the value for nideshop_offline_order_info.outer_service_combo
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setOuterServiceCombo(String outerServiceCombo) {
        this.outerServiceCombo = outerServiceCombo == null ? null : outerServiceCombo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nideshop_offline_order_info.batch_no
     *
     * @return the value of nideshop_offline_order_info.batch_no
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nideshop_offline_order_info.batch_no
     *
     * @param batchNo the value for nideshop_offline_order_info.batch_no
     *
     * @mbggenerated Mon Sep 23 10:05:23 CST 2019
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo == null ? null : batchNo.trim();
    }

    public String getPayChannel() {
        return payChannel;
    }

    public void setPayChannel(String payChannel) {
        this.payChannel = payChannel;
    }

    public String getShroffAccountNumber() {
        return shroffAccountNumber;
    }

    public void setShroffAccountNumber(String shroffAccountNumber) {
        this.shroffAccountNumber = shroffAccountNumber;
    }

    public Long getStoreId() {
        return storeId;
    }

    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    public String getStoreName() {
        return storeName;
    }

    public void setStoreName(String storeName) {
        this.storeName = storeName;
    }

    public String getPayType() {
        return payType;
    }

    public void setPayType(String payType) {
        this.payType = payType;
    }

    public String getStoreAddress() {
        return storeAddress;
    }

    public void setStoreAddress(String storeAddress) {
        this.storeAddress = storeAddress;
    }

    public String getStoreContact() {
        return storeContact;
    }

    public void setStoreContact(String storeContact) {
        this.storeContact = storeContact;
    }
}